server:
  port: 18080
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
logging:
  level:
    root: DEBUG
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(c7mUelq8jY95ypMcEwFWdgTP0XGHMbqkAvXwQAW1K9EjSdWKNZIGmeRFmmQDO3h8QzqhaOHa1wqoWrkNdDeONPV7mFehCe/4iAeZ4PRWOqGklWXNj4oCHhT7U/H8Is96)
            client-secret: ENC(2MCwO76pzHWUU4ZJ5Q1TenqlL4N6T/3w+sv1MZazangGuaJm+EwmRpmkC88hHOuuNyGq5H34hj8=)
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/oauth2/{registrationId}/callback"
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(V7cUnaE1Z0Qo/VBQETxgtUU5NA7BBKsaxyhtP03QGBDHFCFN3Bn8hcl8d6u3MG3al6S6sKdkr8s=)
            client-secret: ENC(HDMIih7PKXsypJI1ZcJ02umjDYXODY6R2ALHKaiya63Xqi2SX8RdHYu6HWDaHSDt0pwxuVOfiY8=)
            scope:
              - profile_nickname
            redirect-uri: "{baseUrl}/api/oauth2/{registrationId}/callback"
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
file:
  upload-path: /Users/kookyungmin/test/todo
jwt:
  atk-expired-time: 1800
#  atk-expired-time: 5
  rtk-expired-time: 1209600
