server:
  port: 18080
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
logging:
  level:
    root: DEBUG
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
file:
  upload-path: /Users/kookyungmin/test/todo
jwt:
  atk-expired-time: 1800